openapi: 3.0.4
info:
  title: Product Service API
  description: A web service that saves products in an asynchronous way.
  version: 1.0.0
servers:
  - url: http://localhost:9292
paths:
  /auth:
    get:
      summary: Log in a user
      responses:
        '200':
          description: User logged in successfully
          headers:
            Set-Cookie:
              description: Cookie for authentication
              type: string
        '400':
          description: Invalid credentials

  /auth/signin:
    post:
      summary: Sign up a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: string
                  example: "user"
                password:
                  type: string
                  example: "password"
      responses:
        '200':
          description: New account created successfully
        '422':
          description: Invalid account details

  /products:
    get:
      summary: Get all products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      example: 1
                    name:
                      type: string
                      example: "Sample Product"
        '401':
          description: Unauthorized - Invalid token

    post:
      summary: Save a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
                  example: 1
                name:
                  type: string
                  example: "New Product"
      responses:
        '202':
          description: Product accepted for processing
        '422':
          description: Invalid product details
        '401':
          description: Unauthorized - Invalid token

  /AUTHORS:
    get:
      summary: Get a static file with the name of the author
      responses:
        '200':
          description: Author name retrieved successfully
          content:
            text/plain:
              schema:
                type: string
                example: "Author Name"
          headers:
            Cache-Control:
              description: Cached for 24 hours
              type: string
              example: "max-age=86400"
        '401':
          description: Unauthorized - Invalid token

  /openapi.yml:
    get:
      summary: Get a static file with the OpenAPI specification of this server
      responses:
        '200':
          description: OpenAPI specification retrieved successfully
          content:
            text/yaml:
              schema:
                type: string
          headers:
            Cache-Control:
              description: Response is never cached
              type: string
              example: "no-cache"
        '401':
          description: Unauthorized - Invalid token
