openapi: 3.0.4
info:
  title: Product Service API
  description: A web service that saves products in an asynchronous way.
  version: 1.0.0
servers:
  - url: http://localhost:9292
tags:
- name: Products
  description: Save and get products
- name: Auth
  description: Authentication
- name: Server
  description: Server Info
paths:
  /auth:
    post:
      summary: Log in a user
      tags:
       - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: string
                  example: "fudo"
                password:
                  type: string
                  example: "fudochallenge"
      responses:
        '200':
          description: User logged in successfully
          headers:
            Set-Cookie:
              schema:
                type: string
              description: Cookie for authentication
        '400':
          description: Invalid credentials

  /auth/signin:
    post:
      summary: Sign in a new user
      tags:
       - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: string
                  example: "user"
                password:
                  type: string
                  example: "password"
      responses:
        '200':
          description: New account created successfully
        '422':
          description: Invalid account details

  /products:
    get:
      summary: Get all products
      tags:
       - Products
      parameters:
        - in: header
          name: Cookie
          schema:
            type: string
            format: name=cookie
          required: true
        - in: header
          name: Accept-Encoding
          schema:
            type: string
            format: encoding-name
          required: false
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      example: 1
                    name:
                      type: string
                      example: "Sample Product"
        '401':
          description: Unauthorized - Invalid token

    post:
      summary: Save a new product
      tags:
       - Products
      parameters:
        - in: header
          name: Cookie
          schema:
            type: string
            format: name=cookie
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
                  example: 1
                name:
                  type: string
                  example: "New Product"
      responses:
        '202':
          description: Product accepted for processing
        '422':
          description: Invalid product details
        '401':
          description: Unauthorized - Invalid token

  /AUTHORS:
    get:
      summary: Get a static file with the name of the author
      tags:
       - Server
      parameters:
        - in: header
          name: Cookie
          schema:
            type: string
            format: name=cookie
          required: true
      responses:
        '200':
          description: Author name retrieved successfully
          content:
            text/plain:
              schema:
                type: string
                example: "Author Name"
          headers:
            Cache-Control:
              schema:
                type: string
              example: "max-age=86400"
              description: Cached for 24 hours
        '401':
          description: Unauthorized - Invalid token

  /openapi.yml:
    get:
      summary: Get a static file with the OpenAPI specification of this server
      tags:
       - Server
      parameters:
        - in: header
          name: Cookie
          schema:
            type: string
            format: name=cookie
          required: true
      responses:
        '200':
          description: OpenAPI specification retrieved successfully
          content:
            text/yaml:
              schema:
                type: string
          headers:
            Cache-Control:
              schema:
                   type: string
              example: "no-cache"
              description: Response is never cached
        '401':
          description: Unauthorized - Invalid token